on:
  push:
  pull_request:
  schedule:
    - cron: '* * 3 * *'

jobs:
  security_checks:
    # runs-on: ubuntu-latest
    runs-on: Ubuntu 22.04
    name: Execute the Duo Dlint action
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.7
    - name: Run Dlint from Duo
      run: |
        python -m pip install --upgrade pip
        cd ./Python
        python3 setup.py install
        pip3 freeze > requirements.txt
        pip3 install dlint
        python3 -m flake8 --select=DUO ./Python
