on: [push]

jobs:
  security_checks:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    name: Execute the pycharm-security action
    steps:
      - uses: actions/checkout@v1
      - name: Run PyCharm Security
        uses: tonybaloney/pycharm-security@master
        with:
          path: Python/
